### ISSUE TITLE
Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by richard-churchman** [jube-home/aml-fraud-transaction-monitoring#45]
2024-06-22 21:13:15,819 Entity Invoke: GUID a7e70157-0002-45d0-8ac3-92d4e65e539c and model 1 has created a general error as System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Jube.Engine.Invoke.EntityAnalysisModelInvoke.WaitReadTasks(List`1 pendingReadTasks) in /home/richard.churchman/RiderProjects/jube/Jube.Engine/Invoke/EntityAnalysisModelInvoke.cs:line 826
   at Jube.Engine.Invoke.EntityAnalysisModelInvoke.Start() in /home/richard.churchman/RiderProjects/jube/Jube.Engine/Invoke/EntityAnalysisModelInvoke.cs:line 748. 

This has been an error that has long since needed attention and relates to counter functionality use of collections for these counter.  More generally the int's should be of a safe type for multi threading and the collections used should be concurrent.  I would prefer to not Sync Lock around bits of code if there is already a tool available.

**Comment by richard-churchman** [comment]
Recent versions,  especially including c12ec4b makes far wider use of Interlocked Increment patterns and lock objects.  Most of such concurrency issues are now resolved.
